import { cp, mkdir, copyFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname, basename } from 'node:path';
const root=new URL('../',import.meta.url),output=new URL('../dist/',import.meta.url);
const rootPath=resolve(fileURLToPath(root)),outputPath=resolve(fileURLToPath(output));
if(dirname(outputPath)!==rootPath || basename(outputPath)!=='dist')throw new Error('Destino de build fora da pasta dist do projeto.');
await rm(outputPath,{recursive:true,force:true});
await mkdir(output,{recursive:true});
for(const directory of ['src','public','scripts','test','docs','.railway'])await cp(new URL(directory,root),new URL(directory,output),{recursive:true});
for(const file of ['package.json','package-lock.json','.env.example','.dockerignore','Dockerfile','README.md','THIRD_PARTY_LICENSES.md','vite.config.js'])await copyFile(new URL(file,root),new URL(file,output));
console.log(`Distribuição Node.js em ${fileURLToPath(output)}. Execute npm ci --omit=dev e npm start nessa pasta.`);
